name: Test

on:
  push:

jobs:
  protostar-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install protostar
        run: |
          curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash

      - name: Update env variables
        run: |
          source /home/runner/.bashrc | bash

      - name: Install protostar dependencies
        run: /home/runner/.protostar/dist/protostar/protostar install

      - name: Compile smart contracts
        run: /home/runner/.protostar/dist/protostar/protostar build

      - name: Run protostar tests
        run: /home/runner/.protostar/dist/protostar/protostar test

      - name: Check interface consistency
        uses: 42labs/starknet-interface-checker-gha@main
        with:
          cairo-path: contracts